
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shopper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - shopper_data:/var/lib/postgresql/data
volumes:
    shopper_data:
        external: true