default: # default connection
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "shopper"
  synchronize: true,
  logging: false,
  entities: [
    "dist/entity/*.js"
  ]
  migrations: [
    "dist/migration/*.js"
  ]
  subscribers: [
   "dist/subscriber/*.js"
  ]